In [88]:
import numpy as np

In [89]:
x=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [91]:
type(x)

numpy.ndarray

In [92]:
x=np.matrix([[0, 1, 2] ,[3, 4, 5], [6, 7, 8]])

In [93]:
x

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [94]:
x[0]

matrix([[0, 1, 2]])

![separator2](https://i.imgur.com/4gX5WFr.png)
### **max/min of raws and columns**
![separator2](https://i.imgur.com/4gX5WFr.png)

In [95]:
max_of_columns=x.max(1)
[k.tolist()[0][0] for k in max_of_columns]


[2, 5, 8]

In [96]:
max_of_rows=x.max(0)
max_of_rows[0].tolist()[0]

[6, 7, 8]

In [97]:
min_of_columns=x.min(1)
[k.tolist()[0][0] for k in min_of_columns]

[0, 3, 6]

In [98]:
min_of_rows=x.min(0)
min_of_rows[0].tolist()[0]

[0, 1, 2]

![separator2](https://i.imgur.com/4gX5WFr.png)
### **mean of columns and rows**
![separator2](https://i.imgur.com/4gX5WFr.png)

In [99]:
mean_columns=x.mean(1)
[k.tolist()[0][0] for k in mean_columns]

[1.0, 4.0, 7.0]

In [100]:
mean_rows=x.mean(0)
mean_rows[0].tolist()[0]

[3.0, 4.0, 5.0]

In [101]:
x.mean()

4.0

![separator2](https://i.imgur.com/4gX5WFr.png)
### **standard deviation columns and rows**
![separator2](https://i.imgur.com/4gX5WFr.png)

In [102]:
std_columns=x.std(1)
[k.tolist()[0][0] for k in std_columns]

[0.816496580927726, 0.816496580927726, 0.816496580927726]

In [103]:
std_rows=x.std(0)
std_rows[0].tolist()[0]

[2.449489742783178, 2.449489742783178, 2.449489742783178]

In [104]:
x.std()

2.581988897471611

![separator2](https://i.imgur.com/4gX5WFr.png)
### **variance columns and rows**
![separator2](https://i.imgur.com/4gX5WFr.png)

In [105]:
var_columns=x.var(1)
[k.tolist()[0][0] for k in var_columns]

[0.6666666666666666, 0.6666666666666666, 0.6666666666666666]

In [106]:
var_rows=x.var(0)
var_rows[0].tolist()[0]

[6.0, 6.0, 6.0]

In [107]:
x.var()

6.666666666666667

![separator2](https://i.imgur.com/4gX5WFr.png)
### **sum columns and rows**
![separator2](https://i.imgur.com/4gX5WFr.png)

In [109]:
sum_columns=x.sum(1)
[k.tolist()[0][0] for k in sum_columns]

[3, 12, 21]

In [110]:
sum_rows=x.sum(0)
sum_rows[0].tolist()[0]

[9, 12, 15]

In [111]:
li=[0,1,2,3,4,5,6,7,8]

In [112]:
li[:3]

[0, 1, 2]

In [113]:
li[3:6]

[3, 4, 5]

In [114]:
li[6:9]

[6, 7, 8]